### ISSUE TITLE
Resolve CONFIGFile issue related to Individual Services

### ISSUE THREAD

**Issue by MFMentopolis** [openBackhaul/M-ApplicationAbbreviationExtractor#18]
- [x] Take the [initial CONFIGFile](https://github.com/openBackhaul/M-ApplicationAbbreviationExtractor/blob/develop/ApplicationAbbreviationExtractor%2Bdata.json)
- [x] For the provided individual service , check weather an operation server is available.
- [x] If there is a missing operation-server , create one.
- [x] Validate the JSON file
- [x] Also provide details about the missing operation-server as a comment in the issue.
- [x] Read [Processing an Issue](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/PreparingSpecifying/ProcessingAnIssue/ProcessingAnIssue.md)
- [x] Read [Creating a Commit](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/PreparingSpecifying/CreatingCommit/CreatingCommit.md)
- [x] Process the Issue you created and commit the changes
- [x] Read [Completing an Issue and creating a Merge Request](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/PreparingSpecifying/CreatingMergeRequest/CreatingMergeRequest.md)
- [x] Push your branch containing your contribution and add a CodeOwner as reviewer
- [ ] Confirm that the CodeOwner merged your contribution 
- [ ] Close this issue

**Comment by MFMentopolis** [comment]
There are three IndividualServices present in the YAML file:
/v1/list-applications-abbreviation:  listApplications
/v1/bequeath-your-data-and-die:  bequeathYourDataAndDie
/v1/start-application-in-generic-representation:  startApplicationInGenericRepresentation

However I don't know how to check if there is an an operation (OAM) server available for each of this individual services.

**Comment by PrathibaJee** [comment]
Yes , we have this 3 individual services in the YAML file , 

1. /v1/start-application-in-generic-representation - aae-1-0-0-op-s-is-000
2. /v1/bequeath-your-data-and-die - aae-1-0-0-op-s-im-000
3. /v1/list-applications-abbreviation - if you search the Config file , you cannot able to find a operation-server for this. But , you can notice a operation server for /v1/list-applications-abbreviation (a spelling mistake). Kindly please modify the operation-name as per the YAML file.

Many thanks.

**Comment by MFMentopolis** [comment]
Hello and thanks very much for the pointers.
I fixed the operation name in the config file from "/v1/list-application-abbreviation" to "/v1/list-applications-abbreviation" (added the "s").

**Comment by PrathibaJee** [comment]
Thanks for fixing the issue. 
I approved and merged the PullRequest , so closing this issue.
