### ISSUE TITLE
Resolve CONFIGFile issue related to UUID

### ISSUE THREAD

**Issue by MFMentopolis** [openBackhaul/M-ApplicationAbbreviationExtractor#41]
- [x] Read [structure of uuid](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/Names/StructureOfUuids/StructureOfUuids.md)
- [x] Take the [initial CONFIGFile](https://github.com/openBackhaul/M-ApplicationAbbreviationExtractor/blob/develop/ApplicationAbbreviationExtractor%2Bdata.json)
- [x] Find the problem in the provided Individual services related to the uuid
- [x] Replace the uuid with proper one
- [x] Validate the JSON file
- [x] Provide details about the UUID in the issue
- [x] Read [Processing an Issue](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/PreparingSpecifying/ProcessingAnIssue/ProcessingAnIssue.md)
- [x] Read [Creating a Commit](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/PreparingSpecifying/CreatingCommit/CreatingCommit.md)
- [x] Process the Issue you created and commit the changes
- [x] Read [Completing an Issue and creating a Merge Request](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/PreparingSpecifying/CreatingMergeRequest/CreatingMergeRequest.md)
- [x] Push your branch containing your contribution and add a CodeOwner as reviewer
- [x] Confirm that the CodeOwner merged your contribution 
- [x] Close this issue

**Comment by MFMentopolis** [comment]
Sorry, I could not find any issue related to the UUID of the configured three individual services other than the application abbreviation starting in upper case letters in the YAML file.

**Comment by PrathibaJee** [comment]
Yes , you are right , the application abbreviation should not be in uppercase.

Also , one more thing needs to be corrected , details as below , 
- The uuid for the individual service "/v1/list-application-abbreviation" is "aae-1-0-0-op-s-im-3001".
- As per the [structure of uuid](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/Names/StructureOfUuids/StructureOfUuids.md) , the sequence number of a uuid should be in 3 digit.
- Here , the sequence number is 3001 , which is wrong.
- So we have to modify the sequence number to 001. (For now I modified the same for your reference)

Kindly please let me know incase of any clarification required or else please close this issue. Many thanks.

**Comment by MFMentopolis** [comment]
OK, thank you pointing this out!
I fixed the "3001" of the uuids in the branch to "001".

**Comment by PrathibaJee** [comment]
Many thanks for fixing the issue. I approved and merged the PR. So , closing this issue.
