### ISSUE TITLE
Resolve CONFIGFile issue related to forwarding construct

### ISSUE THREAD

**Issue by MFMentopolis** [openBackhaul/M-ApplicationAbbreviationExtractor#42]
- [x] Take the [initial CONFIGFile](https://github.com/openBackhaul/M-ApplicationAbbreviationExtractor/blob/develop/ApplicationAbbreviationExtractor%2Bdata.json)
- [x] For the provided individual services , check weather a forwarding is available to redirect the service request (ServiceRequestCausesLoggingRequest)
- [x] If not available , then create a fc-port for the forwarding in the CONFIGFile
- [x] Validate the JSON file
- [x] Also provide details about the missing fc-port as a comment in the issue.
- [x] Read [Processing an Issue](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/PreparingSpecifying/ProcessingAnIssue/ProcessingAnIssue.md)
- [x] Read [Creating a Commit](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/PreparingSpecifying/CreatingCommit/CreatingCommit.md)
- [x] Process the Issue you created and commit the changes
- [x] Read [Completing an Issue and creating a Merge Request](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/PreparingSpecifying/CreatingMergeRequest/CreatingMergeRequest.md)
- [x] Push your branch containing your contribution and add a CodeOwner as reviewer
- [x] Confirm that the CodeOwner merged your contribution 
- [x] Close this issue

**Comment by MFMentopolis** [comment]
There is a forwarding-construct for ServiceRequestCausesLoggingRequest available in the load file:

                        "uuid": "AAE-1-0-0-op-fc-bm-002",
                        "name": [
                            {
                                "value-name": "ForwardingKind",
                                "value": "core-model-1-4:FORWARDING_KIND_TYPE_INVARIANT_PROCESS_SNIPPET"
                            },
                            {
                                "value-name": "ForwardingName",
                                "value": "ServiceRequestCausesLoggingRequest"
                            }
                        ],


So there is no fix needed.

**Comment by PrathibaJee** [comment]
Thanks for looking into this issue.

For the operation-name "/v1/list-application-abbreviation" , we have an operation-server. 
For the uuid of this operation-server a fc-port needs to be created in the ServiceRequestCausesLoggingRequest.
Created a pull request https://github.com/openBackhaul/M-ApplicationAbbreviationExtractor/pull/45 that consists of this change. 
Kindly review that PR to understand the change, and if you have any doubts let me know.
